[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
shop_program = "dtKYr6vLWQR4kYJxRcoFfqv3PtXAtEyZDLJVqzyDwRU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
#cluster = "Localnet"

wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
